config/routes.rb
Rails.application.routes.draw do
  resources :trips  do 
      resources :destinations do 
        member do 
          patch :move
        end
      end
  end
  get '/map', to: 'destinations#map'
  get '/distance', to: 'home#distance'
  get '/distance', to: 'destinations#distance'
  post '/distance', to: 'destinations#distance'
  devise_for :users
  root 'home#pages'
  # root 'trips#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/position.rb
module Position
    extend ActiveSupport::Concern
    included do 
        before_create :set_position
        def set_position
            set_trip()
            max_position = find_max_position()
            self.position = max_position.nil? ? 1 : max_position + 1
          end

        def set_trip
            @trip = Trip.find_by(id: trip_id)
        end

        def find_max_position
          @trip.destinations.maximum(:position)
        end
    end


end

app/models/concerns/validation.rb
module Validation 
    extend ActiveSupport::Concern

    included do 
        validates :name, presence: true
    end


end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :trip
 
  include Validation
  include Position
  
  acts_as_list

  geocoded_by :places 
  after_validation :geocode

  validates :latitude, presence: true
  validates :longitude, presence: true

  def places
    [:address]
  end
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  has_many :destinations, dependent: :destroy
  
  include Validation
 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  
  include Validation
  
  has_many :trips, dependent: :destroy
  has_many :destinations, through: :trips
  
  VALID_EMAIL_REGEX= /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i
  validates :email, uniqueness: {case_sensetive: false}, format: {with: VALID_EMAIL_REGEX, multiline:true}  
  validates_presence_of :email, :phone_number
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
      
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:phone_number,:address])
    end  
end

app/controllers/destination_controller.rb
class DestinationController < ApplicationController
  before_action :authenticate_user!
  before_action :set_destination
    
  def index  
    @destination = @trip.destinations
  end

  def map; end
    
  def distance;end

  def show 
    @destination = @trip.destinations.find_by(id: params[:id])
  end

  def create 
    destination_create = DestinationCreator.new(params[:destination],@trip).create_destination
    if destination_create
      redirect_to trip_path(@trip)
    else
      render :new
    end
  end

  private
  def destination_params
    params.require(:destination).permit(:name,:position, :address, :latitude, :longitude,:starting_address,:end_address)
  end

  def set_destination 
    @trip = Trip.find_by(id: params[:trip_id])
  end
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_destination
    
  def index  
    @destination = @trip.destinations
  end

  def map; end
    
  def distance;end

  def show 
    @destination = @trip.destinations.find_by(id: params[:id])
  end
  def move 
    
    @destination = Destination.find_by(id: params[:id])
    @destination.insert_at!(params[:position].to_i)
    head :ok
  end

  def create 
    destination_create = DestinationCreatorService.new(params[:destination],@trip).create_destination
    if destination_create
      redirect_to trip_path(@trip)
    else
      render :new
    end
  end

  private
  def destination_params
    params.require(:destination).permit(:name,:position, :address, :latitude, :longitude,:starting_address,:end_address)
  end

  def set_destination 
    @trip = Trip.find_by(id: params[:trip_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: %i[ show edit update destroy ]
  before_action :authenticate_user!


  # GET /trips or /trips.json
  def index
    @trips = current_user.trips
  end

  # GET /trips/1 or /trips/1.json
  def show; end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit; end

  # POST /trips or /trips.json
  def create
    @trip = current_user.trips.new(trip_params)
  
    respond_to do |format|
      if @trip.save
        TripCreatorService.new(@trip).mail
        format.html { redirect_to trip_url(@trip), notice: "Trip was successfully created." }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1 or /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to trip_url(@trip), notice: "Trip was successfully updated." }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1 or /trips/1.json
  def destroy
    @trip.destroy

    respond_to do |format|
      format.html { redirect_to trips_url, notice: "Trip was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find_by(id: params[:id])
    end

    # Only allow a list of trusted parameters through.
    def trip_params
      params.require(:trip).permit(:name, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destination_helper.rb
module DestinationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/trips_helper.rb
module TripsHelper
    def prev_destination(destination_trip_id, destination_id) 
        Destination.find_by(trip_id: destination_trip_id,id: destination_id -1)
    end

    def next_destination(destination_trip_id,destination_id)
        Destination.find_by(trip_id: destination_trip_id,id: destination_id + 1)
    end

end

app/views/destination/_new_destination.html.erb
<div class="card mb-3">
  <%= image_tag (asset_path 'ontheroad.png'), class: 'card-img-top img_road' %>

<%= form_for Destination.new(), :url => trip_destination_index_path , method: :post do | form| %>
  <div class="card-body">
		 <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name,class: "input_form" %>
  </div>
  <div>
    <%= form.label :address, style: "display: block"  %>
    <%= form.text_field :address,data: { controller: "address", action: "map-loaded@window->address#initGoogle"} ,class: "input_form"%>
  </div>
  <div>
    <%= form.label :latitude, style: "display: none" %>
    <%= form.text_field :latitude ,class: "input_form",style: "display: none"%>

  </div>
   <div>
    <%= form.label :longitude, style: "display: none" %>
    <%= form.text_field :longitude ,class: "input_form",style: "display: none"%>

  </div>
  <div>
  <br>
      <%= form.button "Create Destination", type: "submit", :class=> "btn  btn-secondary" %>
  </div>

  </div>

  </div>
</div>
<% end %>
<style>
#new_destination{
  text-align: center;
}
.img_road{
    width: 100%;
    height: 20vw;
    object-fit: cover;
  }
.input_form{
  border: 3px solid grey;
  border-radius: 4px;
}
</style>

app/views/destinations/_form_destination.html.erb
<%= form_with(model: @destination) do |form| %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/destinations/_new_destination.html.erb
<div class="card mb-3">
  <%= image_tag (asset_path 'ontheroad.png'), class: 'card-img-top img_road' %>

<%= form_for Destination.new(), :url => trip_destinations_path , method: :post do | form| %>
  <div class="card-body">
		 <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name,class: "input_form" %>
  </div>
  <div>
    <%= form.label :address, style: "display: block"  %>
    <%= form.text_field :address,data: { controller: "address", action: "map-loaded@window->address#initGoogle"} ,class: "input_form"%>
  </div>
  <div>
    <%= form.label :latitude, style: "display: none" %>
    <%= form.text_field :latitude ,class: "input_form",style: "display: none"%>

  </div>
   <div>
    <%= form.label :longitude, style: "display: none" %>
    <%= form.text_field :longitude ,class: "input_form",style: "display: none"%>

  </div>
  <div>
  <br>
      <%= form.button "Create Destination", type: "submit", :class=> "btn  btn-secondary" %>
  </div>

  </div>

  </div>
</div>
<% end %>
<style>
#new_destination{
  text-align: center;
}
.img_road{
    width: 100%;
    height: 20vw;
    object-fit: cover;
  }
.input_form{
  border: 3px solid grey;
  border-radius: 4px;
}
</style>

app/views/destinations/distance.html.erb
<%dest1 = params[:destination][:starting_address]%>
<%dest2 =params[:destination][:end_address]%>
<iframe
  width="1000"
  height="450"
  style="border:2"
  loading="lazy"
  allowfullscreen
  referrerpolicy="no-referrer-when-downgrade"
  src="https://www.google.com/maps/embed/v1/directions?key=<%=Rails.application.credentials.maps%>
    &origin=<%=dest1%>
  &destination=<%=dest2%>">
</iframe>

app/views/destinations/index.html.erb
<h2>Hey <%=current_user.name%></h2>
<h3>Your Trip "<%=@trip.name%>" has <%=@trip.destinations.count%> destinations</h3>
<%total_miles= 0%>
<%@destination.order(position: :asc).each_with_index do |dest,i|%>
    <%if @destination[i+1] == nil%>
        <%city=current_user.address%>
    <%else%>
        <%pos = dest.position + 1%>
        <%destnext = Destination.find_by(trip_id:  @trip.id,position: pos)
%>
    <%end%>
    
    <%dest_cordinates= Geocoder.coordinates(city) || [destnext.latitude,destnext.longitude]%>
    <%distance= dest.distance_to(dest_cordinates).to_i%>
    <%total_miles += distance%>
    <br/>
        <p>Distance between " <%= dest.address  %> " and " <%=city || destnext.address%> " is <strong><%=distance%> miles</strong></p>
        <%=link_to "see Routes " ,map_path(:dest => dest.address,:destnext =>city ||destnext.address)%>
        <br />
        
    <%end%>
    <h3>Your Trip "<%=@trip.name%>" is <%=total_miles%> miles long</h3>

app/views/destinations/map.html.erb
<% @dest1 =params[:dest]%>  
<%@dest2=params[:destnext]%>
<iframe
  width="1000"
  height="450"
  style="border:2"
  loading="lazy"
  allowfullscreen
  referrerpolicy="no-referrer-when-downgrade"
  src="https://www.google.com/maps/embed/v1/directions?key=<%=Rails.application.credentials.maps%>
    &origin=<%=@dest1%>
  &destination=<%=@dest2%>">
</iframe>

app/views/destinations/new.html.erb
<%=render partial: "destinations/new_destination"%>

app/views/destinations/show.html.erb
<%city=current_user.address%>
<%city_cordinates = Geocoder.coordinates(city)%>
<%distance=@destination.distance_to(city_cordinates).to_i%>    
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%=@destination.address%></h5>
        <p class="card-text">Distance between your city and this place is <%=distance%> miles</p>
        <%if @destination.id > 1%>
          <% previous_dest= prev_destination(@destination.trip_id,@destination.id)%>
          <%if previous_dest != nil%>
            <%prev_dest_cordinates =  [previous_dest.latitude,previous_dest.longitude]%>
            <p class="card-text">Distance between your previous destination <%=previous_dest.address%> and this place is <%=@destination.distance_to(prev_dest_cordinates).to_i %> miles</p>
          <%end%>
        <%end%>
        <%if @destination.id < @trip.destinations.all.count%>
            <% next_dest= next_destination(@destination.trip_id,@destination.id)%>
            <%if next_dest != nil%>
              <%next_dest_cordinates = [next_dest.latitude,next_dest.longitude]%>
              <p class="card-text">Distance between your next destination <%=next_dest.address%> and this place is <%=@destination.distance_to(next_dest_cordinates).to_i %> miles</p>
            <%end%>
        <%end%>
      
        <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=14&size=500x450&markers=size:small%7Ccolor:red%7C#{@destination.latitude},#{@destination.longitude}&key=#{Rails.application.credentials.maps}", alt: "Map" %>

        <iframe
          align="right"
          width="500"
          height="450"
          style="border:2"
          loading="lazy"
          allowfullscreen
          referrerpolicy="no-referrer-when-downgrade"
          src="https://www.google.com/maps/embed/v1/directions?key=<%=Rails.application.credentials.maps%>
            &origin=<%=city%>
          &destination=<%=@destination.address%>">
        </iframe>
      </div>
    </div>
<style>
  #map {
      width: 600px;
      height: 400px;
  }
</style>

app/views/home/distance.html.erb
<%= form_for :destination, url: {action: "distance"}, data: {:turbo=> false} do |form| %>
         <div>
    <%= form.label :starting_address, style: "display: block"  %>
    <%= form.text_field :starting_address,id: "destination_address",data: { controller: "address", action: "map-loaded@window->address#initGoogle"} ,class: "input_form"%>
  </div>
         <div>
    <%= form.label :end_address, style: "display: block"  %>
    <%= form.text_field :end_address,id: "test1",data: { controller: "address", action: "map-loaded@window->address#initGoogle"} ,class: "input_form"%>
  </div>
<%=form.submit "See routes"%>
<%end%>

app/views/home/pages.html.erb
<section class="light">
	<div class="container py-2">
		<div class="h1 text-center text-dark" id="pageHeaderTitle">How To Use This App</div>

		<article class="postcard light blue">
			<a class="postcard__img_link" href="#">
				<img class="postcard__img" src="https://picsum.photos/1000/1000" alt="Image Title" />
			</a>
			<div class="postcard__text t-dark">
				<h1 class="postcard__title blue"><a href="#">Add a Trip</a></h1>
				<div class="postcard__subtitle small">
					<time datetime="2020-05-25 12:00:00">
						<i class="fas fa-calendar-alt mr-2"></i><%= DateTime.now.strftime("%b %e %Y")  %>
					</time>
				</div>
				<div class="postcard__bar"></div>
				<div class="postcard__preview-txt">Firstly click on Add Trip in Navbar OR Button below <br /> You will be directed to the next page</div>
				<ul class="postcard__tagbox">
					<li class="tag__item"><i class="fas fa-tag mr-2"></i> <%= link_to "Add Trip", new_trip_path, class: "nav-link active" %></li>
				</ul>
			</div>
		</article>
		<article class="postcard light red">
			<a class="postcard__img_link" href="#">
				<img class="postcard__img" src="https://picsum.photos/501/500" alt="Image Title" />	
			</a>
			<div class="postcard__text t-dark">
				<h1 class="postcard__title red"><a href="#">Add Destinations</a></h1>
				<div class="postcard__subtitle small">
					<time datetime="2020-05-25 12:00:00">
						<i class="fas fa-calendar-alt mr-2"></i><%= DateTime.now.strftime("%b %e %Y")  %>
					
					</time>
				</div>
				<div class="postcard__bar"></div>
				<div class="postcard__preview-txt">Now Here you will add your destinations you wanna go on this roadtrip <br /> But you can firstly check the distance between your cities and the Destinations 
                <br /> Click on Add Destinations
				<ul class="postcard__tagbox">
					<li class="tag__item"><i class="fas fa-tag mr-2"></i>Check Distance between your city and destinations</li>
					<li class="tag__item"><i class="fas fa-tag mr-2"></i><%= link_to "Distance", distance_path %></li>
					
				</ul>
			</div>
		</article>
		<article class="postcard light green">
			<a class="postcard__img_link" href="#">
				<img class="postcard__img" src="https://picsum.photos/500/501" alt="Image Title" />
			</a>
			<div class="postcard__text t-dark">
				<h1 class="postcard__title green"><a href="#">Check Your Routes and Destinations on map</a></h1>
				<div class="postcard__subtitle small">
					<time datetime="2020-05-25 12:00:00">
						<i class="fas fa-calendar-alt mr-2"></i><%= DateTime.now.strftime("%b %e %Y")  %>
					</time>
				</div>
				<div class="postcard__bar"></div>
				<div class="postcard__preview-txt">Now You can check your destination on  map and also you can check the routes bettween your city and destination </div>
				<ul class="postcard__tagbox">
					<li class="tag__item"><i class="fas fa-tag mr-2"></i> <%= link_to "Check Your Destinations", trips_path %></li>
					
				</ul>
			</div>
		</article>
		<article class="postcard light yellow">
			<a class="postcard__img_link" href="#">
				<img class="postcard__img" src="https://picsum.photos/501/501" alt="Image Title" />
			</a>
			<div class="postcard__text t-dark">
				<h1 class="postcard__title yellow"><a href="#">Trip Details</a></h1>
				<div class="postcard__subtitle small">
					<time datetime="2020-05-25 12:00:00">
						<i class="fas fa-calendar-alt mr-2"></i>
				</div>
				<div class="postcard__bar"></div>
				<div class="postcard__preview-txt">Now You can also check trip details and also check details like
                <ul>
                    <li>Distance between Your destinations</li>
                    <li>Total Distance</li>
                    <li>Total Time</li>
                    <li>Fuel Required</li>
                    
                </ul>
                </div>
				<ul class="postcard__tagbox">
					<li class="tag__item"><i class="fas fa-tag mr-2"></i><%= link_to "Check Your Destinations", trips_path %></li>
					
				</ul>
			</div>
		</article>
	</div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TripPlanner</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
   <script>
   window.initMap = ()=> {
    let evt = new Event("map-loaded", {"bubbles":true, "cancelable":true}); 
      evt.preventDefault()
      window.dispatchEvent(evt);    
   }
   </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=<%=Rails.application.credentials.maps%>&libraries=places&callback=initMap" async defer data-turbolinks-eval= "false"></script>
    <%= javascript_importmap_tags %>
    <%= yield(:head_tags) %>

  </head>

  <body>  
  <%= render partial: "shared/navbar" %>
    <%= yield %>
  <div class ='container'>
  </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light   py-md-4" style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <%= link_to "Trip", root_path ,class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <%if user_signed_in? %>
            <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path,data: {"turbo-method": :delete}, class: "nav-link active" %>
            </li>
             <li class="nav-item">
            <%= link_to "Add Trips", new_trip_path, class: "nav-link active" %>
            </li>
             <li class="nav-item">
            <%= link_to "All trips", trips_path , class: "nav-link active"%>
            </li>
        <%else%>
            <li class="nav-item">
            <%=link_to "Sing UP " ,new_user_registration_path,class: "nav-link"%>
            </li>
            <li class="nav-item">
            <%=link_to "Log In " , new_user_session_path,class: "nav-link"%>
            </li>
        <%end%>
       
      </ul>
    </div>
  </div>
</nav>

app/views/trips/_dest_fields.html.erb
<div class='nested-fields'>
  <div class='form-group'>
    <%= form.hidden_field :_destroy %>
		 <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name,class: "input_form" %>
  </div>
  <div>
    <%= form.label :address, style: "display: block"  %>
    <%= form.text_field :address,id: 'destination_address',data: { controller: "address", action: "map-loaded@window->address#initGoogle"} ,class: "input_form"%>
  </div>
  <div>
    <%= form.label :latitude %>
    <%= form.text_field :latitude,id:"destination_latitude" ,class: "input_form "%>

  </div>
   <div>
    <%= form.label :longitude, style: "display: none" %>
    <%= form.text_field :longitude,id: "destination_longitude" ,class: "input_form"%>

  </div>    <small>
      <%= link_to "Remove", "#", data: { action: "click->nested-form#remove_association" } %>
    </small>
  </div>
</div>

app/views/trips/_form.html.erb
<%= form_with(model: trip,class: "trip_form",data: {:turbo=> false}) do |form| %>
  <% if trip.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
        <% trip.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="card mb-3">
  <%= image_tag (asset_path 'ontheroad.png'), class: 'card-img-top img_road' %>

  <div class="card-body">
    <h5 class="card-title">Name</h5>
    <div class="card-text">
    <%= form.text_field :name,class: "input_f" %>
    <br />
    <br />
     <div class="card-text">
      <%= form.button "Create Trip", type: "submit", :class=> "btn  btn-secondary" %>

  </div>
  </div>

  </div>
</div>
<% end %>
<style>
.trip_form{
  text-align: center;
}
.img_road{
    width: 100%;
    height: 20vw;
    object-fit: cover;
  }
.input_f{
  border: 3px solid grey;
  border-radius: 4px;
}
</style>

app/views/trips/_trip.html.erb
<div id="<%= dom_id trip %>">
  <p>
    <strong>Name:</strong>
    <%= trip.name %>
  </p>

  <p>
    <strong>User:</strong>
    <%= trip.user_id %>
  </p>

</div>

app/views/trips/edit.html.erb
<h1>Editing trip</h1>

<%= render "form", trip: @trip %>

<br>

<div>
  <%= link_to "Show this trip", @trip %> |
  <%= link_to "Back to trips", trips_path %>
</div>

app/views/trips/index.html.erb
<section class="light">
  <div class="container py-2">
	<div class="h1 text-center text-dark" id="pageHeaderTitle">All your Trips</div>
       <% @trips.each do |trip| %>
		 <article class="postcard light blue">
			<a class="postcard__img_link" href="#">
				<img class="postcard__img" src="https://picsum.photos/1000/1000" alt="Image Title" />
			</a>
			<div class="postcard__text t-dark">
				<h1 class="postcard__title blue"><a href="#"><%= link_to "#{trip.name}", trip %></a></h1>
				<div class="postcard__subtitle small">
                    <%= link_to "#{"Show Trip"}", trip,class: "btn btn-secondary" %>
					<%= link_to "Add Trip", new_trip_path, class: "btn btn-secondary" %>
				</div>
				<div class="postcard__bar"></div>
				<div class="postcard__preview-txt"></div>	
			</div>
		 </article>
		<%end%>
    </div>
  </div>
<section>      

app/views/trips/new.html.erb
<h1 align="center">New trip</h1>
<%= render "form", trip: @trip %>
<br>
<div>
  <%= link_to "Back to trips", trips_path,class: 'btn  btn-secondary' %>
</div>

app/views/trips/show.html.erb
<br />
<br />
<div class="d-grid gap-2 d-md-flex justify-content-md-between">
  <%= link_to "Add More Destination to the Trip" ,  new_trip_destination_path(@trip),class: "btn btn-secondary"%>
  <%=link_to "Journey Details",trip_destinations_path(:trip_id => @trip.id),class: "btn btn-secondary"%>
  <%= button_to "Destroy this trip", @trip, method: :delete,class: "btn btn-danger" %> 
</div>

<section class="light" >
	<div class="container py-2" data-controller = "drag" data-drag-url ="/trips/:trip_id/destinations/:id/move" id="todos">
		<div class="h1 text-center text-dark" id="pageHeaderTitle">All the Destinations of your Trip <%=@trip.name%>  </div>
          <%all_addresses =[]%>
		  
          <%@trip.destinations.order(position: :asc).each do |destination| %>
		  
            <%all_addresses<<destination.address%>
			<article class="postcard light blue" data-id = "<%= destination.id%>">
					<a class="postcard__img_link" href="#">
					<%= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=14&size=350x350&markers=size:small%7Ccolor:red%7C#{destination.latitude},#{destination.longitude}&key=#{Rails.application.credentials.maps}", alt: "Map" %>
					</a>
					<div class="postcard__text t-dark">
					<h1 class="postcard__title blue"><a href="#"><%=  destination.address%></a></h1>
					<div class="postcard__subtitle ">
						<%if destination.id > 1%>
								<% prev_dest=  prev_destination(destination.trip_id,destination.id)%>
								<%if prev_dest != nil%>
									<%prev_dest_cordinates = [prev_dest.latitude,prev_dest.longitude]%>
									<p class="card-text">Distance between your previous destination <%=prev_dest.address%> and this place is <%=destination.distance_to(prev_dest_cordinates).to_i %> miles</p>
								<%end%>
						<%end%>
						<%if destination.id < @trip.destinations.count%>
								<% next_dest= next_destination(destination.trip_id,destination.id)%>
								<%if next_dest != nil%>
									<%next_dest_cordinates = [next_dest.latitude,next_dest.longitude]%>
									<p class="card-text">Distance between your next destination <%=next_dest.address%> and this place is <%=destination.distance_to(next_dest_cordinates).to_i %> miles</p>
								<%end%>
						<%end%>
						</div>
						<div class="postcard__preview-txt"><%=  destination.address%></div>
						<ul class="postcard__tagbox">
							<li class="tag__item"><i class="fas fa-tag mr-2"></i>  <%=link_to "Details about your Destination",trip_destination_path(destination, :trip_id => @trip.id)%></li>
						</ul>
					</div>
			</article>
          <%end%>
      </div>
    </div>
  <section>      